category: PRODUCTIVITY
defaultLocale: en
localizedSettings:
  displayName: Item Index Manipulator
  pronunciation: Item Index Manipulator
  voice: female_1
projectId: item-index-manipulator
usesInteractiveCanvas: false
